### ISSUE TITLE
Error after running bash connect_clusters on Tier1 using the debug_rome partition (after installing cryosparc)

### ISSUE THREAD

**Issue by tatianawoller** [hpcleuven/cryoSPARC-VSC#2]
``` bash connect_clusters.sh ```

The error I get af
 /vscmnt/leuven_icts/_data_leuven/348/vsc34840/cryoSPARC/cryosparc_master/cryosparc_tools/cryosparc/command.py:135:` UserWarning: *** CommandClient
: (http://debug51.dodrio.os:48402/api) URL Error [Errno 111] Connection refused, attempt 1 of 3. Retrying in 30 seconds                          
  system = self._get_callable("system.describe")()                                                                                               
/vscmnt/leuven_icts/_data_leuven/348/vsc34840/cryoSPARC/cryosparc_master/cryosparc_tools/cryosparc/command.py:135: UserWarning: *** CommandClien$
: (http://debug51.dodrio.os:48402/api) URL Error [Errno 111] Connection refused, attempt 2 of 3. Retrying in 30 seconds                          
  system = self._get_callable("system.describe")()                                                                                               
Traceback (most recent call last):                                                                                                               
  File "/vscmnt/leuven_icts/_data_leuven/348/vsc34840/cryoSPARC/cryosparc_master/cryosparc_tools/cryosparc/command.py", line 105, in func        
    with make_json_request(self, "/api", data=data, _stacklevel=4) as request:                                                                   
  File "/vscmnt/leuven_icts/_data_leuven/348/vsc34840/cryoSPARC/cryosparc_master/deps/anaconda/envs/cryosparc_master_env/lib/python3.10/contextli
b.py", line 135, in __enter__
    return next(self.gen)
  File "/vscmnt/leuven_icts/_data_leuven/348/vsc34840/cryoSPARC/cryosparc_master/cryosparc_tools/cryosparc/command.py", line 226, in make_request
    raise CommandError(error_reason, url=url, code=code, data=resdata)
cryosparc_tools.cryosparc.errors.CommandError: *** (http://debug51.dodrio.os:48402/api, code 500) URL Error [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/vscmnt/leuven_icts/_data_leuven/348/vsc34840/cryoSPARC/cryosparc_master/cryosparc_compute/cluster.py", line 33, in connect
    cli = client.CommandClient(host=os.environ['CRYOSPARC_MASTER_HOSTNAME'], port=int(os.environ['CRYOSPARC_COMMAND_CORE_PORT']))
  File "/vscmnt/leuven_icts/_data_leuven/348/vsc34840/cryoSPARC/cryosparc_master/cryosparc_compute/client.py", line 38, in __init__
    super().__init__(service, host, port, url, timeout, headers, cls=NumpyEncoder)
  File "/vscmnt/leuven_icts/_data_leuven/348/vsc34840/cryoSPARC/cryosparc_master/cryosparc_tools/cryosparc/command.py", line 97, in __in[165/687]
    self._reload()  # attempt connection immediately to gather methods
  File "/vscmnt/leuven_icts/_data_leuven/348/vsc34840/cryoSPARC/cryosparc_master/cryosparc_tools/cryosparc/command.py", line 135, in _reload
    system = self._get_callable("system.describe")()
  File "/vscmnt/leuven_icts/_data_leuven/348/vsc34840/cryoSPARC/cryosparc_master/cryosparc_tools/cryosparc/command.py", line 108, in func
    raise CommandError(
cryosparc_tools.cryosparc.errors.CommandError: *** (http://debug51.dodrio.os:48402, code 500) Encounted error from JSONRPC function "system.descr
ibe" with params ()
/vscmnt/leuven_icts/_data_leuven/348/vsc34840/cryoSPARC/cryosparc_master/cryosparc_tools/cryosparc/command.py:135: UserWarning: *** CommandClient
: (http://debug51.dodrio.os:48402/api) URL Error [Errno 111] Connection refused, attempt 1 of 3. Retrying in 30 seconds
  system = self._get_callable("system.describe")()
/vscmnt/leuven_icts/_data_leuven/348/vsc34840/cryoSPARC/cryosparc_master/cryosparc_tools/cryosparc/command.py:135: UserWarning: *** CommandClient
: (http://debug51.dodrio.os:48402/api) URL Error [Errno 111] Connection refused, attempt 2 of 3. Retrying in 30 seconds
  system = self._get_callable("system.describe")()
Traceback (most recent call last):
  File "/vscmnt/leuven_icts/_data_leuven/348/vsc34840/cryoSPARC/cryosparc_master/cryosparc_tools/cryosparc/command.py", line 105, in func
    with make_json_request(self, "/api", data=data, _stacklevel=4) as request:
  File "/vscmnt/leuven_icts/_data_leuven/348/vsc34840/cryoSPARC/cryosparc_master/deps/anaconda/envs/cryosparc_master_env/lib/python3.10/contextli
b.py", line 135, in __enter__
    return next(self.gen)
  File "/vscmnt/leuven_icts/_data_leuven/348/vsc34840/cryoSPARC/cryosparc_master/cryosparc_tools/cryosparc/command.py", line 226, in make_request
    raise CommandError(error_reason, url=url, code=code, data=resdata)
cryosparc_tools.cryosparc.errors.CommandError: *** (http://debug51.dodrio.os:48402/api, code 500) URL Error [Errno 111] Connection refused

**Comment by stevenvdb** [comment]
Hello Tatiana,

Can you make sure that the cryosparc master is running correctly by checking with `cryosparcm status`? If that is not the case, execute `cryosparcm start` or `cryosparcm restart`.

Two remarks:
- You are using a compute node to run the cryosparc master. This should be possible, but probably you will need to edit the `config.sh` file in your cryosparc master installation and set `export CRYOSPARC_FORCE_HOSTNAME=false` in there. If that variable is set to true, then you will get errors whenever you try to start the cryosparc master on another node than `debug51.dodrio.os`. I would also recommend that before the job ends, you execute `cryosparcm stop`, otherwise processes will be forcefully killed when the job ends and this might give problems when trying to restart cryosparc.
- You installed the cryosparc master in your `$VSC_DATA` directory. In principle this should work but you have to be aware that for Leuven users that directory is physically located in Leuven. Because the cryosparc installation involves a lot of small files and database access, this *might* give performance issues. You can consider installing it in a project directory on Hortense, taking into account the readonly mount as explained in https://docs.vscentrum.be/gent/tier1_hortense.html#accessing-software-via-readonly-mount-point.

**Comment by tatianawoller** [comment]
@stevenvdb : Thank you for your fast answer and feedback. I reinstalled cryosparc in $VSC_SCRATCH_PROJECTS_BASE and added ```export CRYOSPARC_FORCE_HOSTNAME=false``` in ```config.sh```.
I managed to run ``` bash connect_clusters.sh ```  and I managed to start the server using the bioimage desktop (cluster desktop would also have worked.
However, it was not possible to connect to the server  in a browser windows (with google chrome) when using the shell on OOD on Tier-1:
![Screenshot 2024-07-30 133507](https://github.com/user-attachments/assets/4bcf3293-da15-4322-b59f-95a13f11c429)
How do I solve this error ? Do we need to install nx no machine and a SSH agent for a windows laptop?
I started following the introduction tutorial from cryosparc (https://guide.cryosparc.com/processing-data/get-started-with-cryosparc-introductory-tutorial).
Even though I managed to launch a job (I tested two jobs with genius_cpu and genius_gpu_debug), the job is launched but does not run.
![image](https://github.com/user-attachments/assets/3ab8a043-8a3d-43c6-a490-f11a0f9d0ff3)
Could the issue be related to Cryosparc that creates a slurm job using my account of Tier1 for the account and runs it on  Tier2-KUL ?
![image](https://github.com/user-attachments/assets/848be78b-c0f7-4891-aa51-88d538637141)

**Comment by stevenvdb** [comment]
If you start the web server in a bioimage desktop (or cluster desktop), the easiest way to visit the webserver is by opening a brower inside the bioimage desktop (by clicking on "Applications/Web browser", which will open FireFox). If you want to use the browser running on your own machine, you will need to set up a tunnel between your machine and the compute node where the webserver is running. On Windows, you can do this with PuTTY, let me know if you need the instructions to set that up.
On the KU Leuven cluster, you could also connect to the cluster via NoMachine and run the browser there.

The first job (J1) of that tutorial only needs little resources. I am not sure if it is possible to run that one as a job on the cluster. When selecting a lane for J1, just choose the lane named "Master node".
The next job (J2) of the tutorial does require a lot of compute resources, so I would recommend to try job submission there.

The current configuration files will indeed work only for either Hortense or for the KU Leuven Tier-2. In principle, it should be possible to configure everything so it works on both and for instance share the database. That will however need some tweaking. Is your intention to run on both Tier-1 and Tier-2? I will discuss with my colleague Ehsan tomorrow to see how we can proceed.

**Comment by tatianawoller** [comment]
Thank you for your feedback.
Could you provide me the instruction to set-up PUTTY and the instruction for NoMachine (do you need to convert the private key to openssh with keygen?)?
I have modified the connect_cluster.sh to add dodrio-gpu-rome-a100-40 in the cluster list.
Is it easy to create the json and sh files for the debug_rome and dodrio-gpu-rome-a100-80 based on the dodrio-gpu-rome-a100-40  ?
Also can you add cluster such as debug_rome by just rerunning ``` bash connect_clusters.sh``` or do you have to redo the installation?
I have run the first job of the tutorial through the master node and I am waiting for the second job which is queueing.

Currently, my group has credits on both Tier-1 and Tier-2 KU Leuven.
It would indeed be very nice to be able to configure everything so that it works on both Tier-1 and Tier-2.
However, the current configuration files working only for either Hortense or  Tier-2 KU Leuven separately are perfectly fine for us for the moment.

**Comment by stevenvdb** [comment]
The issues mentioned here have been resolved I think, also see https://github.com/hpcleuven/cryoSPARC-VSC/pull/3
